version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ais-infra-common"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-44r43ey3knwx"
s3_prefix = "ais-infra-common"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Environment=\"dev\""
