AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  This stack contains AWS Secrets used for Dynatrace.

Parameters:
  Environment:
    Description: The name of the environment to deploy to
    Type: String
    Default: dev
    AllowedValues:
      - "dev"
      - "build"
      - "staging"
      - "integration"
      - "production"
  ProductTagValue:
    Description: Value for the Product Tag
    Type: String
    Default: GOV.UK One Login
  SystemTagValue:
    Description: Value for the System Tag
    Type: String
    Default: Account Interventions Service
  OwnerTagValue:
    Description: Value for the Owner Tag
    Type: String
    Default: PLACEHOLDER
  SourceTagValue:
    Description: Value for the Source Tag
    Type: String
    Default: govuk-one-login/ais-infra/ais-infra-common/template.yaml

Resources:

  ###########
  # SECRETS #
  ###########

  # see https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3660317070/How+to+add+secure+pipelines+metrics+to+Dynatrace
  DynatraceApiToken:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "/${AWS::StackName}/Dynatrace/Api/Token"
      Description: "Dynatrace API token"
      SecretString: "placeholder-value" #pragma: allowlist secret uses the default aws/secretsmanager key to encrypt the secret string
      Tags:
        - Key: Product
          Value: !Ref ProductTagValue
        - Key: System
          Value: !Ref SystemTagValue
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub "${AWS::StackName}-DynatraceApiToken"
        - Key: Owner
          Value: !Ref OwnerTagValue
        - Key: Source
          Value: !Ref SourceTagValue

  DynatraceApiKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "/${AWS::StackName}/Dynatrace/Metric/Api/Key"
      Description: "Dynatrace Api Key for Namespace Metrics"
      SecretString: "placeholder-value" # pragma: allowlist secret  uses the default aws/secretsmanager key to encrypt the secret string
      Tags:
        - Key: Product
          Value: !Ref ProductTagValue
        - Key: System
          Value: !Ref SystemTagValue
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub "${AWS::StackName}-DynatraceApiKey"
        - Key: Owner
          Value: !Ref OwnerTagValue
        - Key: Source
          Value: !Ref SourceTagValue
