---
default_stages: [ commit ]

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: detect-aws-credentials
        args: [ --allow-missing-credentials ]
      - id: mixed-line-ending
      - id: check-merge-conflict

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
      - id: remove-tabs
      - id: remove-crlf
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: [ '--baseline', '.secrets.baseline' ]

#  - repo: https://github.com/bridgecrewio/checkov.git
#    rev: '2.2.320'
#    hooks:
#      - id: checkov
#        args: [ '--framework', 'cloudformation', '--quiet' ]
#        files: ^(?!\..*).*/template\.(yml|yaml)$
  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v0.72.10  # The version of cfn-lint to use
    hooks:
      - id: cfn-lint
        files: ^(?!\..*).*/template\.(json|yml|yaml)$
